// <auto-generated />
namespace Blog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PostChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PostChange));
        
        string IMigrationMetadata.Id
        {
            get { return "202106181356081_PostChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
